### PR TITLE
bugfix/SDDSIP-1607-uploaded-file-text-size

### PR DESCRIPTION
**Pull request by unutoiul**

### CODE REVIEW

**Review by richard-mohammed-def — CHANGES_REQUESTED** [review]
@unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?

**Comment by unutoiul** [comment]
> @unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?
they are automatically get formatted when saving the file as we worked on adding this functionality is nothing I can do... unless I remove it again...the new format makes more sense... with proper spacings...

**Comment by richard-mohammed-def** [comment]
I recommend turning off format on save when working on legacy files, otherwise this will keep happening. Its not sustainable to have to review entire file changes every time and not be able to see the actual code that has been changed to satisfy the requirements of the ticket.

**Comment by unutoiul** [comment]
> @unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?

I can't because when I save the file automatically re-formats the code...your machine should do the same right? to make sure we have consistency on the files format

**Comment by unutoiul** [comment]
> @unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?

I can't because when I save the file automatically re-formats the code...your machine should do the same right? to make sure we have consistency on the file format

**Comment by unutoiul** [comment]
> @unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?

I can't because when I save the file automatically re-formats the code...your machine should do the same right? to make sure we have consistency on the file format

**Comment by unutoiul** [comment]
> @unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?

I can't because when I save the file automatically re-formats the code...your machine should do the same right? to make sure we have consistency on the files format

**Comment by unutoiul** [comment]
> @unutoiul Because of the formatting changes I can't actually see the changes made related to the ticket itself. Could you just update the lines of code in question rather than format and change the entire file?

I'm happy to do that...but let's sync with the rest of the team to make sure we are doing the right thing moving forward

**Pull request closed without merging**
